# Generated by Django 5.0.3 on 2024-03-08 12:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='phone number is wrong', regex='^\\+998\\d{9}$')])),
                ('type', models.CharField(choices=[('jismoniy', 'jismoniy shaxs'), ('yuridik', 'yuridik shaxs')], default='jismoniy', max_length=250, verbose_name='Type')),
                ('status', models.CharField(choices=[('new', 'new'), ('active', 'active'), ('canseled', 'canseled'), ('moderation', 'moderation')], default='new', max_length=250, verbose_name='Status')),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_type', models.CharField(choices=[('Karta_orqali', 'card'), ('Naqd_pul', 'Naqd pul')], default='Naqd_pul', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('contract', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Contract')),
                ('phone', models.CharField(default='bachelour', max_length=25, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='phone number is wrong', regex='^\\+998\\d{9}$')], verbose_name='Phone')),
                ('type', models.CharField(choices=[('bachelour', 'bachelor'), ('magistr', 'magistr')], default='bachelour', max_length=250, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocatedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_amount', to='common.sponsor', verbose_name='Sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_amount', to='common.students', verbose_name='Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='students',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.university', verbose_name='University'),
        ),
    ]
