# Generated by Django 5.0.3 on 2024-03-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='allocatedamount',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.sponsor', verbose_name='Sponsor'),
        ),
        migrations.AlterField(
            model_name='allocatedamount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.students', verbose_name='Student'),
        ),
    ]
