# Generated by Django 5.0.3 on 2024-03-18 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_allocatedamount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedamount',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_amounts', to='common.sponsor', verbose_name='Sponsor'),
        ),
        migrations.AlterField(
            model_name='allocatedamount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_amounts', to='common.students', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='phone number is wrong', regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.university', verbose_name='students'),
        ),
    ]
