# Generated by Django 5.0.3 on 2024-03-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_allocatedamount_sponsor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='amount',
            new_name='wallet',
        ),
    ]
